info/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

app_name = 'info'
urlpatterns = [
    path('', views.home, name='home'),
    path('faq/', views.faq, name='faq'),
    path('confirmation/', views.visit_confirm, name='confirm'),
]

urlpatterns += staticfiles_urlpatterns()

website/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import JavaScriptCatalog

urlpatterns = [path('admin/', admin.site.urls)]

urlpatterns += i18n_patterns(
    path('', include('info.urls')),
    path('register/', include('user_account.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('book/', include('booking.urls')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
)

info/models.py
from django.db import models


class InfoText(models.Model):
    """Database entry for text on Home page consisting of identifying title and the text"""
    title = models.CharField('Title', max_length=100)
    text = models.TextField('Information text')

    def __str__(self):
        return self.title


class FAQEntry(models.Model):
    """Database entry for a German FAQ entries consisting of question and answer"""
    question_text = models.TextField('Question text', max_length=500)
    answer_text = models.TextField('Answer text', max_length=1000)

    def __str__(self):
        return "Question: " + self.question_text + " - Answer: " + self.answer_text


class FAQEntryEN(models.Model):
    """Database entry for an English FAQ entries consisting of question and answer"""
    question_text = models.TextField('Question text', max_length=500)
    answer_text = models.TextField('Answer text', max_length=1000)

    def __str__(self):
        return "Question: " + self.question_text + " - Answer: " + self.answer_text


class FAQEntryFR(models.Model):
    """Database entry for a French FAQ entries consisting of question and answer"""
    question_text = models.TextField('Question text', max_length=500)
    answer_text = models.TextField('Answer text', max_length=1000)

    def __str__(self):
        return "Question: " + self.question_text + " - Answer: " + self.answer_text


class PriceEntry(models.Model):
    """Database entry for a price entries consisting of an identifying title and the price"""
    title = models.CharField('Title', max_length=100)
    text = models.IntegerField('Price')

    def __str__(self):
        return self.title


class MailEntry(models.Model):
    """Database entry for a mail address entry consisting of an identify title and the mail address"""
    title = models.CharField('Title', max_length=100)
    mail = models.EmailField('Mail', max_length=254)

    def __str__(self):
        return self.title

info/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render

from django.urls import reverse
from user_account.models import Profile
from .models import FAQEntry, InfoText, FAQEntryFR, FAQEntryEN, PriceEntry
from django.utils.translation import get_language


def home(request):
    """
    the view which represents the Home page
    :param request: request used to call website
    :return: the Home Page
    """
    lang = get_language()

    # based on selected language load the correct home text
    if "fr" == lang:
        home_site = get_object_or_404(InfoText, title="HomeFR")
    elif "en" == lang:
        home_site = get_object_or_404(InfoText, title="HomeEN")
    else:
        home_site = get_object_or_404(InfoText, title="Home")
    return render(request, "info/home.html", {'home': home_site})


# reading the questions and answers from the database
def faq(request):
    """
    the view which represents the info site
    :param request: request used to call website
    :return: the info page including FAQ
    """
    lang = get_language()
    inspection = request.GET.get('inspection', '0')

    # choose FAQ entrys based on language chosen
    if "fr" == lang:
        faq_entries = FAQEntryFR.objects.all()
    elif "en" == lang:
        faq_entries = FAQEntryEN.objects.all()
    else:
        faq_entries = FAQEntry.objects.all()

    context = {
        'faq_entries': faq_entries,

        'WSunder503h': get_object_or_404(PriceEntry, title="Week under50 Student 3h"),
        'WSunder506h': get_object_or_404(PriceEntry, title="Week under50 Student 6h"),
        'WSunder509h': get_object_or_404(PriceEntry, title="Week under50 Student 12h"),

        'WSover503h': get_object_or_404(PriceEntry, title="Week over50 Student 3h"),
        'WSover506h': get_object_or_404(PriceEntry, title="Week over50 Student 6h"),
        'WSover509h': get_object_or_404(PriceEntry, title="Week over50 Student 12h"),

        'WnSunder503h': get_object_or_404(PriceEntry, title="Week under50 noStudent 3h"),
        'WnSunder506h': get_object_or_404(PriceEntry, title="Week under50 noStudent 6h"),
        'WnSunder509h': get_object_or_404(PriceEntry, title="Week under50 noStudent 12h"),

        'WnSover503h': get_object_or_404(PriceEntry, title="Week over50 noStudent 3h"),
        'WnSover506h': get_object_or_404(PriceEntry, title="Week over50 noStudent 6h"),
        'WnSover509h': get_object_or_404(PriceEntry, title="Week over50 noStudent 12h"),

        'WES12h': get_object_or_404(PriceEntry, title="Weekend Student 12h"),
        'WES24h': get_object_or_404(PriceEntry, title="Weekend Student 24h"),

        'WEnS12h': get_object_or_404(PriceEntry, title="Weekend noStudent 12h"),
        'WEnS24h': get_object_or_404(PriceEntry, title="Weekend noStudent 24h"),

        'CleaningStudent': get_object_or_404(PriceEntry, title="Cleaning Student"),
        'CleaningNoStudent': get_object_or_404(PriceEntry, title="Cleaning noStudent"),
        'ToiletCleaning': get_object_or_404(PriceEntry, title="Toilet Cleaning"),

        'inspection': inspection,
    }

    if request.POST:
        request_inspection(request)
        return HttpResponseRedirect(reverse('info:confirm'))

        # return render(request, 'info/request_visit.html')

    return render(request, 'info/faq.html', context)


def request_inspection(request):
    """
    function used to request an inspection of the room
    :param request: request used to call the function
    :return: sends all needed emails to the user and the tutor
    """
    user = request.user
    pk = user.pk
    user = Profile.objects.get(pk=pk)
    user.send_visit_email_tutor()


def visit_confirm(request):
    return render(request, 'info/request_visit.html')

info/templates/info/detail.html
<h1>FAQ Entry {{ entry.id }}</h1>
{% load i18n %}
<h2>{%  trans "Frage:" %}</h2>
<p>{{ entry.question_text|linebreaks }}</p>

<h2>{%  trans "Antwort:" %} </h2>
<p>{{ entry.answer_text|linebreaks }}</p>

info/templates/info/faq.html
{% extends 'base_layout.html' %}
{% block content %}
    {% load i18n %}

    {% if faq_entries %}
        <ul>
            {% for entry in faq_entries %}
                <p><h4>{{ entry.question_text }}</h4></p>
            <p>{{ entry.answer_text }}</p>
            <hr id="inspect">
            {% endfor %}
        </ul>
    {% else %}
        <p>{% trans "Keine Fragen." %} </p>
        <hr>
    {% endif %}
    <br><br>
    {% if user.is_authenticated %}
    <form method="post">
        {% csrf_token %}
        {%if inspection == '1'%}


                 {%  blocktrans %} Sind Sie sich sicher, dass Sie eine Besichtigung anfragen möchten? Wir werden uns dann per Mail mit Ihnen in Verbindung setzen.{%endblocktrans%} <br>

                <button type="submit" style="margin: 20px;" name="{{entry}}" class="btn btn-info"> {%  trans "JA" %}</button>
                <a class="btn btn-info" href="?inspection=0#inspect"> {%  blocktrans %}Abbrechen{%endblocktrans %}</a>
        {% else %}
                 {% blocktrans %} Möchten Sie einen Termin zur Raumbesichtigung vereinbaren? {%  endblocktrans %}
                 <a href="?inspection=1#inspect" class="btn btn-info">{%  trans "Besichtigungstermin anfragen" %}</a>
        {% endif %}
    </form>
    <br><br><hr>
    {% endif %}
    <br>
    <table class="table table-bordered">
   <header> {%trans "Unter der Woche stehen Ihnen folgende Möglichkeiten zur Verfügung. Alle Preise sind in Euro gegeben." %}</header>
        <thead>
        <tr>
            <th scope="col">{% trans "Dauer" %}</th>
            <th scope="col" colspan="4">{% trans "Unter der Woche (Mo, Di, Mi, Do, Fr)" %}</th>

        </tr>
        </thead>
        <tbody>
        <tr>
            <th scope="row"> </th>
            <th scope="row" colspan="2">{% trans "Student" %} </th>
            <th scope="row" colspan="2">{% trans "kein Student" %} </th>

        </tr>
        <tr>
        <tr>
            <th scope="row"> Personenzahl:</th>
            <th scope="row">{% trans "unter 50" %} </th>
            <th scope="row">{% trans "über 50" %} </th>
            <th scope="row">{% trans "unter 50" %} </th>
            <th scope="row">{% trans "über 50" %} </th>

        </tr>
        <tr>
            <th scope="row">{% trans "bis 3 Stunden" %} </th>
            <td> {{WSunder503h.text }}</td>
            <td> {{  WSover503h.text}}</td>
            <td> {{  WnSunder503h.text }}</td>
            <td>{{  WnSover503h.text  }}</td>

        </tr>
        <tr>
            <th scope="row">{% trans "bis 6 Stunden" %}</th>
            <td>{{  WSunder506h.text }}</td>
            <td> {{  WSover506h.text}}</td>
            <td>{{  WnSunder506h.text}}</td>
            <td>{{ WnSover506h.text }}</td>

        </tr>
        <tr>
            <th scope="row">{% trans "bis 12 Stunden" %}</th>
            <td>{{ WSunder509h.text }}</td>
            <td>{{   WSover509h.text}}</td>
            <td> {{  WnSunder509h.text }}</td>
            <td> {{  WnSover509h.text }}</td>

        </tr>
        </tbody>
    </table>
    <br>
    <table class="table table-bordered">
    <header> {%trans "Am Wochenende stehen Ihnen folgende Möglichkeiten zur Verfügung. Alle Preise sind in Euro gegeben." %}</header>
        <thead>
        <tr>
            <th scope="col">{% trans "Dauer" %}</th>
            <th scope="col" colspan="2">{% trans "Am Wochenende (Sa, So)" %}</th>

        </tr>
        </thead>
        <tbody>
        <tr>
            <th scope="row"> </th>
            <th scope="row" >{% trans "Student" %} </th>
            <th scope="row" >{% trans "kein Student" %} </th>

        </tr>

        <tr>
            <th scope="row">{% trans "bis 12 Stunden" %} </th>
            <td >{{  WES12h.text }}</td>
            <td >{{WEnS12h.text }}</td>


        </tr>
        <tr>
            <th scope="row">{% trans "bis 24 Stunden" %}</th>
            <td >{{WES24h.text }}</td>
            <td >{{WEnS24h.text}}</td>
        </tr>


        </tbody>
    </table>

    <br><hr><br>
    <strong> {% blocktrans  with t1=ToiletCleaning.text c1=CleaningStudent.text c2=CleaningNoStudent.text %} Bitte beachten Sie, dass unter der Woche bei Buchungen, die nach 22 Uhr enden, zusätzlich {{ t1 }} € Reinigungsgebühr anfällt und dass am Wochenende grundsätzlich eine Endreinigungsgebühr in Höhe von {{ c1 }} € (Student) bzw. {{ c2 }} € (sonst) anfällt. {% endblocktrans %} </strong>

{% endblock content %}

info/templates/info/home.html
{% extends 'base_layout.html' %}
{% load i18n %}
{% block content %}
<h1> {% trans "Willkommen beim FORUM international!" %} </h1>

{{ home.text|linebreaks }}

{% endblock %}

info/templates/info/index.html
{% load i18n %}

<h1>{% trans "{{ home.title }}" %}</h1>

{{ home.text }}

info/templates/info/request_visit.html
{% extends 'base_layout.html' %}
{% load i18n %}


{% block content %}
    <h1 style="text-align:center;">  {% blocktrans %} Besichtigung angefordert {% endblocktrans %}</h1>

    <br>
    <div style="text-align: center;">
        <div style="display: inline-block; text-align: left;">
           {% blocktrans %} Sie haben eine Besichtigung angefragt. Wir werden uns in Kürze per Mail mit Ihnen in Verbindung setzen. {% endblocktrans %}<br>
           {% blocktrans %} Bei weiteren Fragen wenden Sie sich bitte an: {% endblocktrans %}<a href="mailto:info@example.com">info@example.com</a>.
           {% blocktrans %} Hier gehts zurück:{% endblocktrans %} <a href="{% url 'info:faq' %}"> FAQ </a>  <br>

        </div>
    </div>

{% endblock %}