booking/urls.py
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from booking.forms import BookingForm
from . import views

app_name = 'booking'
urlpatterns = [
    url(r'^calendar$', views.CalendarView.as_view(), name='calendar'),
    url(r'^event/edit/(?P<event_datum>[\d-]+)/(?P<event_time>[\d:]+)/(?P<event_dur>\d+)$', views.event,
        name='event_edit'),
    url(r'^ajax/validate_price/$', views.calculate_price_ajax, name='validate_price'),
    url(r'^confirmation/', views.book_confirm, name='confirm'),
    url(r'^waitinglist/(?P<date>[\d-]+)$', views.request_waiting_list_addition, name='request_waitinglist'),
]
urlpatterns += staticfiles_urlpatterns()

info/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

app_name = 'info'
urlpatterns = [
    path('', views.home, name='home'),
    path('faq/', views.faq, name='faq'),
    path('confirmation/', views.visit_confirm, name='confirm'),
]

urlpatterns += staticfiles_urlpatterns()

website/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import JavaScriptCatalog

urlpatterns = [path('admin/', admin.site.urls)]

urlpatterns += i18n_patterns(
    path('', include('info.urls')),
    path('register/', include('user_account.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('book/', include('booking.urls')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
)

booking/models.py
from abc import abstractmethod
from datetime import timedelta
from enum import Enum

from django.db import models
from django.contrib.auth.models import User
from django.db.models import Q
from django.db.models.signals import pre_save, pre_delete
from django.dispatch import receiver
from django.template.loader import render_to_string
from django.utils.datetime_safe import datetime
from django.utils import timezone
from docxtpl import DocxTemplate
from django.utils.translation import gettext_lazy as _
from django.core.mail import send_mail
from django.core.mail import EmailMessage
from django.utils.translation import get_language
import datetime as dt
from user_account.models import Profile
from django import forms
import django.utils.timezone as tz

from info.models import PriceEntry, MailEntry
from website import settings
from django.core.exceptions import ValidationError


class Event(models.Model):
    """Abstract representation of an event"""
    date = models.DateField(_('Datum'), help_text=_('Bitte wählen Sie ein Datum aus.'))
    start_time = models.TimeField(_('Beginn'), help_text=_('Bitte wählen Sie eine Uhrzeit aus.'))

    duration = models.SmallIntegerField(_('Dauer'), help_text=_('Bitte wählen Sie die gewünschte Dauer.'))

    # Internal fields
    start_datetime = models.DateTimeField(default='', editable=False)
    end_datetime = models.DateTimeField(default='', editable=False)
    booking_time = models.DateTimeField(default=timezone.now, editable=False)

    # Fill internal fields
    def save(self, *args, **kwargs):
        self.start_datetime = datetime.combine(self.date, self.start_time)
        self.end_datetime = self.start_datetime + dt.timedelta(hours=self.duration)
        super().save(*args, **kwargs)

    def update(self, *args, **kwargs):
        super().save(*args, **kwargs)

    @abstractmethod
    def is_blocker(self):
        pass


class WaitingList(models.Model):
    """Abstract representation of a waiting list for a certain date"""
    date = models.DateField("Datum", default="2019-01-01")  # the date of the waiting list
    waiting = models.ManyToManyField(Profile)  # users waiting for this date to get free

    def remind_customers(self):
        for customer in self.waiting.all():
            # construct and send email message to the customer
            context = {
                'date': self.date,
                'customer': customer,
            }

            mail_text = render_to_string('mails/customer_waiting_list.txt', context=context)

            send_mail(
                'Warteliste FORUM International ' + self.date.strftime("%d.%m.%Y"),
                mail_text,
                settings.EMAIL_HOST_USER,
                [customer.email],
                fail_silently=False,
            )


class Blocker(Event):
    """Class used to block timeslots without a booking"""

    def is_blocker(self):
        return True

    def __str__(self):
        return 'Blocker vom {}, {}, {}'.format(self.date, self.start_time, self.duration)


class Booking(Event):
    """Representation of a booking"""
    YES_NO = [
        ("yes", _("JA")),
        ("no", _("NEIN")),
    ]

    student = models.CharField(_('Student (UdS/HTW)'), choices=YES_NO, max_length=10,
                               default='',
                               help_text=_('Bitte geben Sie an, ob Sie Student der UdS oder der HTW sind.'))

    number_people = models.SmallIntegerField(_('Personenzahl'),
                                             help_text=_(
                                                 'Bitte geben Sie an, wie viele Personen etwa erscheinen werden.   '))

    refrigerator = models.CharField(_('Kühlschränke erwünscht?'), choices=YES_NO, max_length=10,
                                    default='',
                                    help_text=_(
                                        'Bitte geben Sie an, ob Sie die Kühlschränke des FORUM international benutzen möchten.'))

    occasion = models.TextField(_('Anlass'), max_length=40,
                                default='', help_text=_('Bitte geben Sie einen Anlass an.'))

    confirmed = models.BooleanField(_('Bestätigt'), default=False, help_text='')
    rent_paid = models.BooleanField(_('Miete bezahlt'), default=False, help_text='')
    contract_signed = models.BooleanField(_('Vertrag unterschrieben'), default=False, help_text='')
    deposit_paid = models.BooleanField(_('Kaution gezahlt'), default=False, help_text='')
    deposit_refunded = models.BooleanField(_('Kaution zurückerstattet'), default=False, help_text='')

    requested_inspection = models.BooleanField(_('Besichtigung beantragt'), default=False, help_text='')

    author = models.ForeignKey(User, default=None, on_delete=models.PROTECT)

    def save(self, *args, **kwargs):
        # self.start_datetime = datetime.combine(self.date, self.start_time)
        # self.end_datetime = self.start_datetime + dt.timedelta(hours=self.duration)
        super().save(*args, **kwargs)

    def update(self, *args, **kwargs):
        super().update(*args, **kwargs)

    def __str__(self):
        return 'Buchung vom {}, {}, {}'.format(self.date, self.start_time, self.duration)

    def calculate_price_event(self):
        """Calculate and return the price for the event."""
        return calculate_price(self.date, str_to_bool(self.student), self.duration, self.number_people,
                               self.end_datetime,
                               str_to_bool(self.refrigerator))

    def generate_contract(self):
        """Generate the contract for the event and save it in /data/generated_contracts/date_authorid.docx."""
        template = open("data/contract_template.docx", "rb")
        contract = DocxTemplate(template)

        if (self.date - self.booking_time.date()) < dt.timedelta(days=14):
            return_date = (self.booking_time + dt.timedelta(days=1)).strftime("%d.%m.%Y")
        else:
            return_date = (self.booking_time + dt.timedelta(days=7)).strftime("%d.%m.%Y")

        if self.refrigerator == 'yes':
            included = 'Toilettennutzung und Kühlhaus'
        else:
            included = 'Toilettennutzung'

        context = {
            'customer': self.author.profile,
            'start_datetime': self.start_datetime.strftime("%d.%m.%Y, %H:%M"),
            'end_datetime': self.end_datetime.strftime("%d.%m.%Y, %H:%M"),
            'duration': self.duration,
            'price': self.calculate_price_event(),
            'deposit': PriceEntry.objects.get(title='Deposit').text,
            'current_date': self.booking_time.strftime("%d.%m.%Y"),
            'return_date': return_date,
            'tutor_mail': MailEntry.objects.get(title='Tutor').mail,
            'included': included,
        }

        contract.render(context)
        contract.save(
            'data/generated_contracts/contract_' + self.start_datetime.__str__() + '_' + str(self.author_id) + '.docx')

    def generate_bill(self):
        """Generate the contract for the event and save it in /data/generated_bills/date_authorid.docx."""
        # Check if day is a weekday
        day_type = get_day_type(self.start_datetime)

        if day_type == 'WEEKEND' or (self.end_datetime.time() > dt.time(22, 0, 0)
                                     or self.end_datetime.time() < dt.time(8, 0, 0)):
            toilet = "inkl. Nutzung der Toiletten im FORUM International"

        else:
            toilet = "Toilettennutzung der Mensa im Erdgeschoss, D4.1"

        template = open("data/bill_template.docx", "rb")
        bill = DocxTemplate(template)
        context = {
            'customer': self.author.profile,
            'bill_id': self.id,
            'current_year': self.booking_time.strftime("%Y"),
            'customer_title': self.author.profile.title,
            'customer_lastname': self.author.profile.last_name,
            'start_datetime': self.start_datetime.strftime("%d.%m.%Y, %H:%M"),
            'end_datetime': self.end_datetime.strftime("%d.%m.%Y, %H:%M"),
            'duration': self.duration,
            'price': self.calculate_price_event(),
            'current_date': self.booking_time.strftime("%d.%m.%Y"),
            'toilet': toilet
        }

        bill.render(context)
        bill.save(
            'data/generated_bills/bill_' + self.start_datetime.__str__() + '_' + str(self.author_id) + '.docx')

    def is_blocker(self):
        """Return if the booking is a blocker."""
        return False

    def send_email_caretaker(self):
        """If refrigeration is needed, send mail to the caretaker mail address saved in database including all info."""
        # check if refrigerator is needed and if yes send email to caretaker
        if self.refrigerator:
            # get date and time of event
            date = self.date.strftime("%d.%m.%Y")
            time = self.start_time.strftime("%H:%M")

            # construct and send email message to caretaker
            context = {
                'date': date,
                'time': time,
            }
            mail_text = render_to_string('mails/caretaker.txt', context=context)
            send_mail(
                'Buchung FORUM international ' + date,
                mail_text,
                settings.EMAIL_HOST_USER,
                [MailEntry.objects.get(title='Caretaker').mail],
                fail_silently=False,
            )
        return

    def send_cancellation_email_caretaker(self):
        """
        If refrigeration was needed, send cancellation mail to the caretaker mail address
        saved in database including all info.
        """
        # check if refrigerator was needed and if yes send email to caretaker
        if self.refrigerator:
            # get date and time of event
            date = self.date.strftime("%d.%m.%Y")
            time = self.start_time.strftime("%H:%M")

            # construct and send email message to caretaker
            context = {

booking/forms.py
from django.core.exceptions import ValidationError
from django.forms import Textarea

from django.forms import ModelForm
from django.utils.datetime_safe import datetime
from dateutil.relativedelta import relativedelta
from django.utils.translation import gettext_lazy as _

import datetime as dt

from booking.models import Booking, timeslot_available, get_day_type


class BookingForm(ModelForm):
    class Meta:
        model = Booking
        # datetime-local is a HTML5 input type, format to make date time show on fields
        widgets = {
            'occasion': Textarea(attrs={'rows': '3'})
        }
        fields = ['date', 'start_time', 'duration', 'student', 'number_people', 'refrigerator', 'occasion']

    # this function will be used for the validation
    def clean(self):
        # fetch data from form
        super(BookingForm, self).clean()

        start_date = self.cleaned_data.get('date')
        start_time = self.cleaned_data.get('start_time')
        duration = self.cleaned_data.get('duration')
        student = self.cleaned_data.get('student')
        number_people = self.cleaned_data.get('number_people')
        refrigerator = self.cleaned_data.get('refrigerator')
        occasion = self.cleaned_data.get('occasion')

        validate_input(start_date, start_time, duration, student, number_people, refrigerator, occasion)

        return self.cleaned_data

    def __init__(self, *args, **kwargs):
        super(BookingForm, self).__init__(*args, **kwargs)

        self.fields['date'].widget.attrs['readonly'] = True
        self.fields['date'].help_text = None
        self.fields['start_time'].widget.attrs['readonly'] = True
        self.fields['start_time'].help_text = None
        self.fields['duration'].widget.attrs['readonly'] = True
        self.fields['duration'].help_text = None


def validate_input(start_date, start_time, duration, student, number_people, refrigerator, occasion):
    start_datetime = datetime.combine(start_date, start_time)
    end_datetime = start_datetime + dt.timedelta(hours=duration)
    today = datetime.today()
    if start_datetime < today:
        raise ValidationError(_('You cant book events in the past'), 'unavailable_timeslot')
    today += relativedelta(months=+6)
    if start_datetime > today:
        raise ValidationError(_('You cant book so far in the future'), 'unavailable_timeslot')
    if not timeslot_available(start_datetime, end_datetime):
        raise ValidationError(_('Es gibt bereits eine Buchung zu diesem Zeitpunkt.'), 'unavailable_timeslot')

    day_type = get_day_type(start_date)
    if (day_type == 'WEEKDAY') and duration not in [3, 6, 12]:
        raise ValidationError(_('An Wochentagen ist nur eine 3-,6- oder 12-stündige Buchung möglich.'),
                              'invalid_duration')
    elif (day_type == 'WEEKEND') and duration not in [12, 24]:
        raise ValidationError(_('An Wochenenden ist nur eine 12- oder 24-stündige Buchung möglich.'),
                              'invalid_duration')

    if start_time < dt.time(8, 0):
        raise ValidationError(_('Eine Buchung ist erst ab 8 Uhr (Mo-Fr) bzw. 16 Uhr (Sa-So) möglich.'))

    if start_time.minute != 0:
        raise ValidationError(_('Buchungen können nur zur vollen Stunde beginnen.'), 'invalid_starttime')

    if number_people <= 0:
        raise ValidationError(_('Die Anzahl erscheinender Personen muss größer als 0 sein.'), 'invalid_people_num')

    if student != 'yes' and student != 'no':
        raise ValidationError(_('Ungültige Eingabe bei Studentenfrage.'), 'invalid_student_input')

    if refrigerator != 'yes' and refrigerator != 'no':
        raise ValidationError(_('Ungültige Eingabe bei Kühlschrankfrage.'), 'invalid_refrigerator_input')

    if occasion == '':
        raise ValidationError(_('Das Feld zum Anlass darf nicht leer sein.'), 'empty_occasion')

booking/templates/booking/book.html
{% extends 'base_layout.html' %}
{% load i18n %}
{% block content %}
    {% if user.is_authenticated %}
        {#  calendar that was used: https://www.huiwenteo.com/normal/2018/07/29/django-calendar-ii.html#}
        <div class="container">
            <div class="row">
                <div class="col-sm-4">
                    <div class="clearfix">
                        {% if not date_in_past_month %}
                            <a class="btn btn-secondary float-left" role="button"
                               href="{% url 'booking:calendar' %}?{{ prev_month }}#month"> < {{ prev_month_name }}  </a>
                        {% endif %}
                        {% if not six_month_ahead %}
                            <a class="btn btn-secondary float-right" role="button"
                               href="{% url 'booking:calendar' %}?{{ next_month }}#month"> {{ next_month_name }} > </a>
                        {% endif %}
                    </div>
                    <table border="0" cellpadding="0" cellspacing="0" class="calendar">
                        {{ calendar }}
                    </table>
                    <br>
                    <p> {% trans "Verfügbarkeit:" %}</p>
                    <span style="background-color:green">  &nbsp;  &nbsp; </span> {% trans "Verfügbar" %}
                    <span style="background-color:rgb(204,204,0)">  &nbsp;  &nbsp; </span> {% trans "Geringe Verfügbarkeit" %}
                    <br>
                    <span style="background-color:red">  &nbsp;  &nbsp; </span> {% trans "Ausgebucht" %}
                    <span style="background-color:grey">  &nbsp;  &nbsp; </span> {% trans "Nicht buchbar" %}
                    <br>
                    <br>
                    <br>
                </div>
                {% if not dur_chosen %}
                    <div class="col">
                        {% if durationlist %}
                            <p> {% trans "Ihr gewähltes Datum: " %} <b>{{ datum.date }} </b></p>
                            <p> {% trans "Bitte wählen Sie die gewünschte Dauer Ihrer Buchung:" %} <br></p>
                            <ul>
                                {% for entry in durationlist %}

                                    <a class="btn btn-secondary btn-block " role="button"
                                       href="{{ request.get_full_path }}&dur={{ entry }}">{{ entry }} {% trans "Stunden" %}</a>
                                {% endfor %}
                            </ul>
                        {% elif datum %}
                            <p> {% trans "Ihr gewähltes Datum: " %} <b>{{ datum.date }} </b></p>
                            <p> {% blocktrans %} Leider ist dieser Tag bereits ausgebucht. Sie können sich in die
                                Warteliste
                                eintragen, um eine Benachrichtigung zu erhalten, sobald ein Termin frei geworden ist.
                            {% endblocktrans %} </p>
                            <a class="btn btn-primary" role=button"
                               href="{% url 'booking:request_waitinglist' date=datum.date %}"> {% trans "Auf Warteliste setzen" %}</a>
                        {% endif %}
                    </div>
                {% else %}
                    <a id="dayselected"></a>
                    {% if free_timeslots %}
                        <div class="col">
                            <div class="row" >
                                <div class="col">
                                    <ul>
                                        <p> {% trans "Ihr gewähltes Datum: " %} <b>{{ datum.date }} </b></p>
                                        <p> {% trans "Die Dauer Ihrer Buchung beträgt: " %}
                                            <b>{{ dur }} {% trans "Stunden" %} </b>
                                        </p>
                                        <br>
                                        <p> {% trans "Bitte wählen Sie das gewünschte Zeitfenster Ihrer Buchung:" %}</p>
                                        <br>
                                        {% for start,end in free_timeslots.items %}

                                            <a class="btn btn-secondary btn-block" role=button"
                                               href="{% url 'booking:event_edit' event_datum=datum.date  event_time=start event_dur=dur %}">
                                                {{ start }} - {{ end }}</a>
                                        {% endfor %}
                                    </ul>

                                </div>

                                <div class="col">
                                    <ul>
                                        <p>&nbsp;</p>
                                        <p>&nbsp;</p>
                                        <br>

                                        <p>{% trans "Diese Zeitfenster sind leider nicht mehr verfügbar:" %} </p><br>
                                        {% for start,end in blocked_timeslots.items %}

                                            <button type="button" class="btn btn-secondary btn-block"
                                                    disabled> {{ start }}
                                                - {{ end }}</button>

                                        {% endfor %}

                                    </ul>

                                </div>
                            </div>


                            <div class="row">
                                <br>
                                <br>
                                <br>
                                <p> <b>{% trans "Gewünschter Termin nicht dabei?" %}</b><br>
                                    {% trans "Sie können sich in die Warteliste eintragen, um eine Benachrichtigung zu erhalten, sobald ein Termin frei geworden ist. " %}
                                    <br>
                                    <br>
                                    <a class="btn btn-primary " role=button"
                                       href="{% url 'booking:request_waitinglist' date=datum.date %}"> {% trans "Auf Warteliste setzen" %}</a>
                                </p>
                            </div>
                        </div>

                    {% else %}
                        <p> {% trans "Wir können leider kein freies Zeitfenster zu Ihren Angaben finden." %} </p>
                    {% endif %}
                {% endif %}

            </div>
        </div>
    {% else %}
        <p>{% trans "Bitte melden Sie sich an um den Raum zu buchen" %} <a
                href="{% url 'login' %}"> {% trans "Anmelden" %} </a></p>
        <p>{% trans "Sie haben noch keinen Account?" %} <a
                href="{% url 'register_user' %}"> {% trans "Registrieren" %}</a></p>


    {% endif %}
    <a id="selectioncomplete"></a>
{% endblock %}

booking/templates/booking/book_confirm.html
{% extends 'base_layout.html' %}
{% load i18n %}


{% block content %}
    <h1 style="text-align:center;"> {% trans "Vielen Dank für Ihre Buchung." %}</h1>

    <br>
    <div style="text-align: center;">
        <div style="display: inline-block; text-align: left;">
            {% blocktrans %} Sie erhalten Ihre Buchungsbestätigung per E-Mail an: {% endblocktrans %} {{ user.email }}. <br>
            {%  trans "Ihre Buchung ist unter" %}<a href="{% url 'myaccount_edit' %}"> {% trans "Mein Account" %} </a> {% trans "einsehbar" %}.<br> <br>
            {% blocktrans %} Bei weiteren Fragen wenden Sie sich bitte an:{% endblocktrans %} <a href="mailto:info@example.com">info@example.com</a>.
        </div>
    </div>

{% endblock %}

booking/templates/booking/event.html
{% extends "base_layout.html" %}
{% load i18n %}

{% block javascript %}
    <script>
        document.getElementById("validate_number_people").style.display = "none";
        document.getElementById("text_after_calculation").style.display = "none";

        calculate = function () {
            document.getElementById("info_calc_price").style.display = "none";
            var number_people = $("#id_number_people").val();
            if (number_people.length == 0) {
               document.getElementById("validate_number_people").style.display = "block";
                return;
            }
            document.getElementById("validate_number_people").style.display = "none";
            document.getElementById("text_after_calculation").style.display = "block";
            var date = $("#id_date").val();
            var student = $("#id_student").val();
            var duration = $("#id_duration").val();
            var start_time = $("#id_start_time").val();

            $.ajax({
                url: '{% url "booking:validate_price" %}',
                data: {
                    'number_people': number_people,
                    'date': date,
                    'student': student,
                    'duration': duration,
                    'start_time': start_time,
                },
                dataType: 'json',
                success: function (data) {
                    document.getElementById('id_price').value = data.price
                }
            })
        }
    </script>
{% endblock %}




{% block content %}
    <div class="clearfix">
        <a class="btn btn-info left" href="{% url 'booking:calendar' %}">{% trans "Kalender"  %}</a>
    </div>

    <form method="post">
        {% csrf_token %}
        <table class="form form-table">
            {{ form }}
        </table>


        <!--<button type="submit" class="btn btn-info right"> {% trans "Absenden" %} </button> -->



    <p> <input type="button"  class="btn btn-info right" value="{% blocktrans %}Preisberechnung{% endblocktrans %}" onclick="calculate()"></p><br>
    <p id="validate_number_people" align="right" style="color:red;"> {% blocktrans %} Bitte füllen Sie das Formular vollständig aus {%endblocktrans %} </p>
    <text id="info_calc_price"> {% blocktrans %} Um die Buchung abzuschließen, berechnen Sie bitte zuerst den Preis. {% endblocktrans %}</text>

    <div id="text_after_calculation">
        <b> {% blocktrans %} Bitte beachten Sie, dass eine Kaution im Wert von  {% endblocktrans%}<div style=" color:red;font-weight: bold; display:inline" >200€ </div>
           {% blocktrans %} hinterlegt werden muss.  {% endblocktrans%}</b> <br>
        <b> {% blocktrans %} Der Preis Ihrer Buchung beträgt: {% endblocktrans%} </b>
        <div style="color:red;font-weight: bold; display:inline">
        <output id="id_price"> </output> € <br>
        </div>
        {% blocktrans %} Wenn Sie mit der Buchung fortfahren möchten, drücken Sie auf Absenden. Sie können noch bis 5 Tage vor dem gebuchten Datum die Buchung kostenfrei stornieren. {% endblocktrans %}
       <br>
        <button type="submit" class="btn btn-info right"> {% trans "Absenden" %} </button>
    </div>

    </form>
{% endblock %}

booking/templates/booking/waiting_list_addition.html
{% extends 'base_layout.html' %}
{% load i18n %}


{% block content %}
    <h1 style="text-align:center;">  {% blocktrans %} Sie wurden auf die Warteliste gesetzt! {% endblocktrans %}</h1>

    <br>
    <div style="text-align: center;">
        <div style="display: inline-block; text-align: left;">
           {% blocktrans %} Sie wurden auf die Warteliste gesetzt. Sobald eine Buchung an für diesen Tag storniert wird, werden wir Sie per Mail darüber informieren. {% endblocktrans %}<br>
           {% blocktrans %} Bei weiteren Fragen wenden Sie sich bitte an: {% endblocktrans %}<a href="mailto:info@example.com">info@example.com</a>.

        </div>
    </div>

{% endblock %}