info/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

app_name = 'info'
urlpatterns = [
    path('', views.home, name='home'),
    path('faq/', views.faq, name='faq'),
    path('confirmation/', views.visit_confirm, name='confirm'),
]

urlpatterns += staticfiles_urlpatterns()

website/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import JavaScriptCatalog

urlpatterns = [path('admin/', admin.site.urls)]

urlpatterns += i18n_patterns(
    path('', include('info.urls')),
    path('register/', include('user_account.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('book/', include('booking.urls')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
)

templates/base_layout.html
{% load static from staticfiles %}
{% load i18n %}
{% load django_simple_cookie_consent_tags %}

<!DOCTYPE html>
<html>
<head>

    <link rel="stylesheet" type="text/css" href="{% static 'cal.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css1.css' %}"/>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <title>FORUM international</title>

    {% display_cookie_consent %}

</head>
<body>


{#LOGO#}
<div class="d-flex">
    <div class="mr-auto p-2">
        <a href="{% url 'info:home' %}">
            <img style="height:auto; max-width:55%;" src="{% static "header/forum_logo.jpg" %}" alt="logo">
        </a>
    </div>
    <div class="p-2">
        <img style="height:auto; max-width:30%; float:right" src="{% static "header/logo.PNG" %}" alt="logo">
    </div>

</div>
{# Sprache#}


<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">

    {#  <a class="navbar-brand" href="#">FORUM</a>#}
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">
            <li class="nav-item {% if request.resolver_match.view_name == 'info:home' %}active{% endif %}"><a
                    class="nav-link" href="{% url 'info:home' %}">Home</a></li>

            <li class="nav-item {% if request.resolver_match.view_name == 'info:faq' %}active{% endif %}"><a
                    class="nav-link" href="{% url 'info:faq' %}"> {% trans "Informationen" %}</a></li>
            <li class="nav-item {% if request.resolver_match.view_name == 'booking:calendar' %}active{% endif %}"><a
                    class="nav-link" href="{% url 'booking:calendar' %}"> {% trans "Mieten" %}</a></li>
            {% if user.is_authenticated %}
                <li class="nav-item {% if request.resolver_match.view_name == 'myaccount_edit' %}active{% endif %}"><a
                        class="nav-link" href="{% url 'myaccount_edit' %}">{% trans "Mein Account" %}</a></li>
            {% endif %}

        </ul>

        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'logout' %}">{% trans "Abmelden" %}</a>
                {% else %}
                    <a class="nav-link" href="{% url 'login' %}" class="">{% trans "Anmelden" %}</a>
                {% endif %}
            </li>
        </ul>

        <ul class="navbar-nav right">
            <li class="dropdown nav-item">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Choose language
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="/de/">Deutsch</a>
                    <a class="dropdown-item" href="/en/">English</a>
                    <a class="dropdown-item" href="/fr/">Français</a>
                </div>
            </li>
        </ul>


    </div>
</nav>

{#NAVBAR#}


{#GALLERY#}
<div class="gallery-row">
    <div class="gallery-column"><img src="{% static 'header/forum_gallery1.jpg' %}" alt="Image 1"></div>
    <div class="gallery-column"><img src="{% static 'header/forum_gallery2.jpg' %}" alt="Image 2"></div>
    <div class="gallery-column"><img src="{% static 'header/forum_gallery3.jpg' %}" alt="Image 3"></div>
    <div class="gallery-column"><img src="{% static 'header/forum_gallery4.jpg' %}" alt="Image 4"></div>
</div>
<a id="month"></a>
{#CONTENT#}
<div class="container" style="margin-top:30px;margin-bottom:70px">
    <div class="row">
        <div class="col-sm-12">
            {% block content %}
            {% endblock content %}

        </div>
    </div>
</div>




<!-- Footer -->
<footer class="page-footer sticky-top bg-dark sticky-top text-light" id="footer">

    <!-- Footer Links -->
    <div class="container-fluid text-center text-md-left">

        <!-- Grid row -->
        <div class="row">

            <!-- Grid column -->
            <div class="col-md-4 mt-md-0 mt-3">

                <!-- Content -->
                <p class="text">
                    Zentrale des Beispiels im Saarland e. V.<br>
                    Campus Beispiel<br>
                    Gebäude Z 1.1<br>
                    12345 Beispiel

                </p>
                <p class="phone">
                    {% trans "Telefon:" %} <a style="color:white; text-decoration: underline;" href="tel:01234/567891">01234/567891</a><br>
                    {% trans "Fax:" %} <a style="color:white; text-decoration: underline;" href="tel:01234/567891">01234/567891</a>
                </p>
                <p class="email">
                    <a href="mailto:info@example.com" style="color:white; text-decoration: underline;">info@example.com</a>
                </p> </p>

            </div>
            <!-- Grid column -->

            <hr class="clearfix w-100 d-md-none pb-3">

            <!-- Grid column -->
            <div class="col-md-4 mb-md-0 mb-4">


                <div class="info-wrapper">
                    <p class="text">
                        Beispiel im Saarland e. V.<br>
                        Außenstelle Beispiel<br>
                        Universitätsklinikum des Beispiels Gebäude 99 <br>
                        45678 Beispiel
                    </p>
                    <p class="phone">
                        {% trans "Telefon:" %} <a style="color:white; text-decoration: underline;"
                                                  href="tel:01234/567891">01234/567891</a><br>
                        {% trans "Fax:" %} <a style="color:white; text-decoration: underline;"
                                              href="tel:01234/567891">01234/567891</a>
                    </p>
                    <p class="email">
                        <a href="mailto:info@example.com"
                           style="color:white; text-decoration: underline;">info@example.com</a>
                    </p>
                </div>


            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-3 mb-md-0 mb-3">

                <div class="socialmedia-wrapper">

                    <p class="text"> {% trans "Das Beispiel im Saarland e.V. ist jetzt auch bei Facebook und Instagram zu finden." %} </p>

                </div>

            </div>
            <!-- Grid column -->

        </div>
        <!-- Grid row -->

    </div>
    <!-- Footer Links -->


</footer>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
{% block javascript %}{% endblock %}


</body>
</html>